### ISSUE TITLE
Projection does not work across list of subdocuments

### ISSUE THREAD

**Issue by Bernie** [mongomock/mongomock#287]
When attempting to project a subset of fields from a list of subdocuments, MongoMock fails to properly emulate MongoDB behaviour, when occurring both in the find and aggregate use cases.

Take this test document as an example:

`{'a': 1, 'b': [{'c': 3, 'd': 4}, {'c': 5, 'd': 6}]}`

When performing a find operation in MongoDB, and projecting only one of the fields from the subdocument, for instance, field 'b.c', MongoDB returns field 'c' across all subdocuments in the list:

`find_one({'a': 1}, {'b.c': 1})`:

`{'_id': ObjectId('587795f7b0c3993ebd9219fb'), 'b': [{'c': 3}, {'c': 5}]}`

The same behaviour applies when projecting in an aggregation:

`aggregate([{'$match': {'a': 1}}, {'$project': {'b.c': 1}}])`:

`{'_id': ObjectId('587795f7b0c3993ebd9219fb'), 'b': [{'c': 3}, {'c': 5}]}`

However, this breaks in MongoMock.

When performed during the find operation, an empty dict is returned instead of a list of projected subdocuments:

`{'b': {}, '_id': ObjectId('5877922eb0c3993dcebdf17d')}`

When the same projection is applied in the aggregation, the aggregation operation fails with an exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mongomock/collection.py", line 1586, in aggregate
    out_collection = _extend_collection(out_collection, field, value)
  File "mongomock/collection.py", line 1464, in _extend_collection
    doc[field] = _parse_expression(expression.copy(), doc)
AttributeError: 'int' object has no attribute 'copy'
```

**Comment by Bernie** [comment]
I have a fix for this, however it does not match MongoDB behaviour exactly when projections are requests that do not match the documents structure.

However, it appears to behave more closely to MongoDB than before, as it now supports list of subdocuments properly.
