### ISSUE TITLE
Can't have leading dollar-sign in documents

### ISSUE THREAD

**Issue by jbremer** [mongomock/mongomock#313]
The following fails on real MongoDB instances, but succeeds in `mongomock`.

```python
>>> import mongomock
>>> mongomock.MongoClient().db.temporary.insert({"$foo": "bar"})
ObjectId('58cd310ecd23ff0534b5fd83')
>>> import pymongo
>>> pymongo.MongoClient().db.temporary.insert({"$foo": "bar"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 1926, in insert
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 436, in _insert
bson.errors.InvalidDocument: key '$foo' must not start with '$'
```

**Comment by jbremer** [comment]
Same for other invalid types, actually. The document should probably be validated.

```python
>>> import pymongo
>>> import mongomock
>>> mongomock.MongoClient().db.temporary.insert({"a": {"b"}})
ObjectId('58cd322fcd23ff76de522fce')
>>> pymongo.MongoClient().db.temporary.insert({"a": {"b"}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 1926, in insert
  File "build/bdist.linux-x86_64/egg/pymongo/collection.py", line 436, in _insert
bson.errors.InvalidDocument: Cannot encode object: set(['b'])
```

**Comment by DeoLeung** [comment]
@mdomke I think it will be much easier to add the `bson` package to the project and do all these checks.

**Comment by pcorpet** [comment]
This is now implemented.
