### ISSUE TITLE
cannot handle $filter (aggregation) { input: <array>, as: <string>, cond: <expression> }

### ISSUE THREAD

**Issue by liyuqi** [mongomock/mongomock#336]
run aggregate pipeline 

```
{   "$project": {
        "TOTAL": {"$size": "$DATA"},
        "COUNT": {
               "$size": {"$filter": {
                   "input": "$DATA",
                   "as": "data",
                   "cond": {"$eq": ["$$data.TF", False]},
                }}
         }
     }
}
```
if shows error:

```
Traceback (most recent call last):
  File "UnitChecker.py", line 54, in test_check
    results = Checker.check(doc, self.mock_db)
  File "Checker.py", line 45, in check
    agg_result = list(db.Collection.aggregate(pipeline))
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1627, in aggregate
    out_collection = _extend_collection(out_collection, field, value)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1506, in _extend_collection
    doc[field] = _parse_expression(expression.copy(), doc)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1487, in _parse_expression
    value_dict[k] = _parse_expression(v, doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1487, in _parse_expression
    value_dict[k] = _parse_expression(v, doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1487, in _parse_expression
    value_dict[k] = _parse_expression(v, doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1483, in _parse_expression
    return _handle_comparison_operator(k, v, doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1396, in _handle_comparison_operator
    return _parse_expression(values[0], doc_dict) == \
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1474, in _parse_expression
    return _parse_basic_expression(expression, doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/collection.py", line 1468, in _parse_basic_expression
    return get_value(doc_dict)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/helpers.py", line 214, in g
    return recurse_embedded(obj, item)
  File "/usr/local/lib/python2.7/dist-packages/mongomock/helpers.py", line 207, in recurse_embedded
    ret = ret[k]
KeyError: 'data'
```

ref:
[https://docs.mongodb.com/manual/reference/operator/aggregation/filter/](https://docs.mongodb.com/manual/reference/operator/aggregation/filter/)

**Comment by pcorpet** [comment]
@liyuqi if you please, review #448 so that I can merge it.
