### ISSUE TITLE
Update the egg for 3.8.0

### ISSUE THREAD

**Issue by shackra** [mongomock/mongomock#360]
My project is a module and it have specified mongomock 3.8.0 for testing, the best match that setuptools can find is 3.0 which is buggy in respect to `collection.count` method, if I hack my setuptools entry point to download the archive of 3.8.0 setuptools complains with the following:

```
Searching for mongomock==3.8.0
Downloading https://github.com/mongomock/mongomock/archive/3.8.0.zip#egg=mongomock-3.8.0
Best match: mongomock 3.8.0
Processing 3.8.0.zip
Writing /tmp/easy_install-o90c2zas/mongomock-3.8.0/setup.cfg
Running mongomock-3.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-o90c2zas/mongomock-3.8.0/egg-dist-tmp-t6beykae
Not found: ['https://github.com/mongomock/mongomock/archive/3.8.0.zip#egg=mongomock-3.8.0']

Installed /tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/tmp/easy_install-o90c2zas/mongomock-3.8.0/.eggs/pbr-3.1.1-py3.6.egg/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is
 a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mongomock was given, but was not
 able to be found.                                                                                                                               
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-o90c2zas/mongomock-3.8.0/setup.cfg: Exception: Versioning 
for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between th
e package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mongomock was given, but was not able to be found.
```

**Comment by pcorpet** [comment]
Is this still an issue? I wasn't able to reproduce

**Comment by shackra** [comment]
I have to check, brb...

**Comment by pcorpet** [comment]
> brb

Holding my breath :wink:

**Comment by shackra** [comment]
It is:

```
$ python setup.py test
running test
Searching for mongomock>=3.8.0
Reading https://pypi.python.org/simple/mongomock/
No local packages or working download links found for mongomock>=3.8.0
error: Could not find suitable distribution for Requirement.parse('mongomock>=3.8.0')

```

**Comment by pcorpet** [comment]
Curious, I managed to make it work on a simple test. Can you check for me the version of python you are using (`python --version`), as well as the version of setuptools (`pip show setuptools`)?

For me it works with Python 3.7.0 and setuptools v40.0.0.

I'm ok to try fixing it for older verisons, but I'd like to reproduce your usecase so I'm sure what to fix.

**Comment by shackra** [comment]
My setuptools is older:

```
jorge@sanson-gnu ~/proyectos/mondongo
(mondongodev) > $ python --version
Python 3.6.6

jorge@sanson-gnu ~/proyectos/mondongo
(mondongodev) > $ pip show setuptools
Name: setuptools
Version: 36.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /home/jorge/.virtualenvs/mondongodev/lib/python3.6/site-packages
Requires: 
Required-by: zope.interface, importmagic

jorge@sanson-gnu ~/proyectos/mondongo
(mondongodev) > $ 
```

**Comment by pcorpet** [comment]
Please update to setuptools>=38, I was able to reproduce your error and upgrading it to 38.7.0 was enough.
