### ISSUE TITLE
Method doesn`t have validation if document fields is value None or not.

### ISSUE THREAD

**Issue by AndrewKhodyakov** [mongomock/mongomock#368]
Hello, I use mongomock for my tests - it is very usefull!

But I got some problem with filters gt\ly\dte\lte execution.
If I save document which look like this: `{'some_value': None}` 
and then try to apply filter - `{'some_value':{'gt': 0}}` to this collection - I
get the exception:

> Traceback (most recent call last):
  File "/home/ajet/work_repo/nlp_store/src/tests/flask_tests.py", line 294,
in test_e_therapies_tree_build
    data=json.dumps(tmp))
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/werkzeug/test.py",
line 788, in post
    return self.open(*args, **kw)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/testing.py",
line 127, in open
    follow_redirects=follow_redirects)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/werkzeug/test.py",
line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/werkzeug/test.py",
line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/werkzeug/test.py",
line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/eve/flaskapp.py",
line 1033, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1985, in wsgi_app
    response = self.handle_exception(e)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/_compat.py",
line 33, in reraise
    raise value
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/_compat.py",
line 33, in reraise
    raise value
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/flask/app.py",
line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/eve/endpoints.py",
line 63, in collections_endpoint
    return send_response(resource, response)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/eve/render.py",
line 66, in decorated
    getattr(app, event_name + '_' + resource)(request, r)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/events/events.py",
line 77, in __call__
    f(*a, **kw)
  File "/home/ajet/work_repo/nlp_store/src/app.py", line 20, in
post_therapies_tree_post_callback
    app.logger)
  File "/home/ajet/work_repo/nlp_store/src/tree.py", line 31, in
increase_left_right
    {'$inc': {'left': 2, 'right' : 2}})
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/collection.py",
line 366, in update_many
    multi=True),
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/collection.py",
line 389, in _update
    for existing_document in itertools.chain(self._iter_documents(spec),
[None]):
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/collection.py",
line 947, in <genexpr>
    if filter_applies(filter, document))
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/filtering.py",
line 44, in filter_applies
    for operator_string, search_val in iteritems(search)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/filtering.py",
line 44, in <genexpr>
    for operator_string, search_val in iteritems(search)
  File
"/home/ajet/.virtualenvs/nlp_store/lib/python3.6/site-packages/mongomock/filtering.py",
line 156, in <lambda>
    return lambda v, l: (v is not NOTHING or v is not None) and f(v, l)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

So I follow through exceptions stack and find out that in module
***mongomock/filtering.py (master branch)*** in line  ***148*** returned lambda did`t has
None validation. I add next line and this solve the problem:

`return lambda v, l: v is not NOTHING and v is not None and f(v, l)`

**Comment by pcorpet** [comment]
I have a proper fix in #415. I've tried your exact usecase and it did not raise any error.
