### ISSUE TITLE
mongomock+mongoengine update_one error

### ISSUE THREAD

**Issue by nullscc** [mongomock/mongomock#458]
I have encountered a problem when using mongomock to run some tests. But it is just ok when I use a real mongdb server address.

## environment
```
python 3.6.5
mongoengine==0.15.3
pymongo==3.7.1
mongomock==3.12.0
```

## code sample
```
from mongoengine import *
from mongoengine.fields import *

class Test(Document):
    meta = {
        'db_alias': 'aa',
        'collection': 'tt'
    }

    userid = StringField(required=True)
    remark = StringField(required=False, default='')

    @classmethod
    def update_by_id(cls, id, **kwargs):
        return cls.objects.filter(id=id).update_one(**kwargs)

connect(alias='aa', host='mongomock://127.0.0.1')
# connect(alias='aa', host='mongodb://127.0.0.1')
tid = str(Test(userid='123').save().id)
print(Test.update_by_id(tid, remark='test zero'))
```

## traceback
When I run the code showed above, the error happens:
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    print(Test.update_by_id(tid, remark='test zero'))
  File "test.py", line 15, in update_by_id
    return cls.objects.filter(id=id).update_one(**kwargs)
  File "/Users/null/.virtualenvs/sibbay_fc/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 585, in update_one
    upsert=upsert, multi=False, write_concern=write_concern, **update)
  File "/Users/null/.virtualenvs/sibbay_fc/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 526, in update
    with set_write_concern(queryset._collection, write_concern) as collection:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/null/.virtualenvs/sibbay_fc/lib/python3.6/site-packages/mongoengine/context_managers.py", line 226, in set_write_concern
    yield collection.with_options(write_concern=WriteConcern(**combined_concerns))
  File "/Users/null/.virtualenvs/sibbay_fc/lib/python3.6/site-packages/mongomock/collection.py", line 1917, in with_options
    if value is not None and value != default_value:
  File "/Users/null/.virtualenvs/sibbay_fc/lib/python3.6/site-packages/pymongo/write_concern.py", line 119, in __ne__
    return self.__document != other.document
AttributeError: 'NoneType' object has no attribute 'document'
```

Any help will be appreciated!

**Comment by pcorpet** [comment]
Hi @nullscc, thanks for reporting. This is indeed a bug of mongomock. I'll fix it ASAP.

**Comment by nullscc** [comment]
@pcorpet Thank you for watching this so soon, I have taken it a try and it indeed worked.

**Comment by jezeniel** [comment]
Already encountered this one, when will this be pushed on pypi?

**Comment by jezeniel** [comment]
@pcorpet the I also tested the develop branch, it worked.

**Comment by pcorpet** [comment]
Thanks @jezeniel , I'll try to finish 2 pending PRs and will release tonight.
