### ISSUE TITLE
mongomock.patch from the README fails

### ISSUE THREAD

**Issue by ikhlestov** [mongomock/mongomock#511]
while executing simple snippet from the README:

```python
import mongomock
import pymongo


@mongomock.patch(servers=(('localhost', 27017),))
def test_increate_votes_endpoint():
    objects = [dict(votes=1), dict(votes=2), ...]
    client = pymongo.MongoClient('localhost')
    client.db.collection.insert_many(objects)
    call_endpoint('/votes')
```

I've got the following error:

```
Traceback (most recent call last):
  File "fail_mongomock.py", line 5, in <module>
    @mongomock.patch(servers=(('localhost', 27017),))
  File "/Users/illarionkhliestov/Projects/mongomock_fail/.venv/lib/python3.6/site-packages/mongomock/patch.py", line 67, in patch
    parsed_servers.update(_parse_any_host(server))
  File "/Users/illarionkhliestov/Projects/mongomock_fail/.venv/lib/python3.6/site-packages/mongomock/patch.py", line 26, in _parse_any_host
    return split_hosts(host)
  File "/Users/illarionkhliestov/Projects/mongomock_fail/.venv/lib/python3.6/site-packages/pymongo/uri_parser.py", line 252, in split_hosts
    for entity in hosts.split(','):
AttributeError: 'tuple' object has no attribute 'split'
```

my test env is:

```
Python 3.6.7 (default, Feb  7 2019, 18:06:27)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
mongomock==3.16.0
pymongo==3.7.2
sentinels==1.0.0
six==1.12.0
```

After brief debugging, it seems that [split_hosts](https://github.com/mongomock/mongomock/blob/develop/mongomock/patch.py#L26) method should be called not with tuple argument (hosts, port), but with extracted arguments like `split_hosts(*host)`

**Comment by pcorpet** [comment]
Thanks for reporting and sorry for not commenting here earlier. I've fixed this in 554ce59
