### ISSUE TITLE
$where is not working in find query

### ISSUE THREAD

**Issue by vikashupadhyay** [mongomock/mongomock#513]
I have seeded some data using mongomock, but when I am trying to find some document using $where clause but not returning anything.

**Comment by pcorpet** [comment]
Hi @vikashupadhyay thanks for reporting. This is both a feature request (because $where is not implemented in mongomock yet) and a bug (because $mongomock should report that instead of returning silently).

Can you please provide a simple example?

**Comment by kurthaegeman** [comment]
Simple example (as in the mongoengine issue I mistakenly opened, referenced here above):
```python
class IntPair(Document):
  fielda = IntField()
  fieldb = IntField()

a = IntPair(fielda=1, fieldb=1)
b = IntPair(fielda=1, fieldb=2)
c = IntPair(fielda=2, fieldb=1)
a.save()
b.save()
c.save()
query = IntPair.objects.where('this[~fielda] >= this[~fieldb]')
results = list(query)
```

Resulting exception stack trace:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kurt/temp/venv/lib/python3.8/site-packages/mongoengine/queryset/queryset.py", line 62, in __len__
    list(self._iter_results())
  File "/Users/kurt/temp/venv/lib/python3.8/site-packages/mongoengine/queryset/queryset.py", line 110, in _iter_results
    self._populate_cache()
  File "/Users/kurt/temp/venv/lib/python3.8/site-packages/mongoengine/queryset/queryset.py", line 129, in _populate_cache
    self._result_cache.append(next(self))
  File "/Users/kurt/temp/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1590, in __next__
    raw_doc = next(self._cursor)
  File "/Users/kurt/temp/venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1671, in _cursor
    self._cursor_obj.where(where_clause)
AttributeError: 'Cursor' object has no attribute 'where'
```

Version info:
mongoengine==0.20.0
mongomock==3.19.1.dev17
pymongo==3.10.1
