### ISSUE TITLE
TypeError when a value used in an index is not hashable (e.g. a dict)

### ISSUE THREAD

**Issue by anon4777** [mongomock/mongomock#562]
Mongomock crashes when using GenericReferenceField in an index. MongoDB can create the index without any errors. Sample code:

```py
    import mongoengine
    from mongoengine import Document, StringField, IntField, GenericReferenceField
    ALIAS = "my_alias"

    class Content(Document):

        parent = GenericReferenceField()
        slug = StringField(required=True, max_length=90)
        title = StringField(required=True, max_length=60)
        sort_index = IntField(default=50)

        meta = {
            'allow_inheritance': True,
            'db_alias': ALIAS,
            'collection': 'content',
            'indexes': [
                {
                    "fields": ['parent', 'slug'],
                    "unique": True
                },
                ('parent', '+sort_index'),
            ],
            'ordering': ['+sort_index'],}

    class Foo(Content):

        pass

    class Bar(Content):

        pass

    def bootstrap_data():

        foo = Foo(slug="slug1", title="title1")
        foo.save()
        print("object saved", foo.to_json())

        bar2 = Bar(parent=foo, slug="slug2", title="title2", sort_index=2)
        bar2.save()
        print("object saved", bar2.to_json())
        bar3 = Bar(parent=foo, slug="slug3", title="title3", sort_index=3)
        bar3.save()
        print("object saved", bar3.to_json())


    # using MongoDB, comment if unused
    database = mongoengine.connect(ALIAS, host="localhost")
    mongoengine.register_connection(alias=ALIAS, name=ALIAS, host="localhost", username="some_username", password="some_password", authentication_source="some_db")
    bootstrap_data()

    # using mongomock, comment if unused
    database = mongoengine.connect(ALIAS, host="mongomock://localhost")
    mongoengine.register_connection(alias=ALIAS, host="mongomock://localhost")
    bootstrap_data()
```

Output when using MongoDB v4.0.12:

```sh
    object saved {"_id": {"$oid": "5d72637583896c8ee0fef5f1"}, "_cls": "Content.Foo", "slug": "slug1", "title": "title1", "sort_index": 50}
    object saved {"_id": {"$oid": "5d72637583896c8ee0fef5f2"}, "_cls": "Content.Bar", "parent": {"_cls": "Content.Foo", "_ref": {"$ref": "content", "$id": {"$oid": "5d72637583896c8ee0fef5f1"}}}, "slug": "slug2", "title": "title2", "sort_index": 2}
    object saved {"_id": {"$oid": "5d72637583896c8ee0fef5f3"}, "_cls": "Content.Bar", "parent": {"_cls": "Content.Foo", "_ref": {"$ref": "content", "$id": {"$oid": "5d72637583896c8ee0fef5f1"}}}, "slug": "slug3", "title": "title3", "sort_index": 3}
```

Output when using mongomock 3.17.0:

```sh
    object saved {"_id": {"$oid": "5d7262ee61b3fb3ec3863a6d"}, "_cls": "Content.Foo", "slug": "slug1", "title": "title1", "sort_index": 50}
    object saved {"_id": {"$oid": "5d7262ee61b3fb3ec3863a6e"}, "_cls": "Content.Bar", "parent": {"_cls": "Content.Foo", "_ref": {"$ref": "content", "$id": {"$oid": "5d7262ee61b3fb3ec3863a6d"}}}, "slug": "slug2", "title": "title2", "sort_index": 2}
    Traceback (most recent call last):
        bootstrap_data()
        bar3.save()
    File "mongoengine/document.py", line 383, in save
        self.ensure_indexes()
    File "mongoengine/document.py", line 888, in ensure_indexes
        collection.create_index(fields, background=background, **opts)
    File "mongomock/collection.py", line 1389, in create_index
        if index in indexed:
    TypeError: unhashable type: 'dict'
```

Mongoengine version is 0.18.2.

**Comment by pcorpet** [comment]
Thanks for the report. I've dug down and found that the trouble was index values containing dicts. I'll send a fix ASAP.
