### ISSUE TITLE
Test failure in 3.19.0

### ISSUE THREAD

**Issue by felixonmars** [mongomock/mongomock#604]
I got the following test failure since the upgrade to 3.19.0:

```
======================================================================
FAIL: test__insert_do_not_modify_input (tests.test__collection_api.CollectionAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-mongomock/src/mongomock-3.19.0/tests/test__collection_api.py", line 4743, in test__insert_do_not_modify_input
    self.assertEqual(
AssertionError: 946722630012 != 946719030012.0

----------------------------------------------------------------------
Ran 679 tests in 0.395s
```

Interestingly the value differs on different machine so it could be a timezone issue? The one above is a UTC+1 machine, and the one below is on a UTC+8 one:

```
======================================================================
FAIL: test__insert_do_not_modify_input (tests.test__collection_api.CollectionAPITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-mongomock/src/mongomock-3.19.0/tests/test__collection_api.py", line 4743, in test__insert_do_not_modify_input
    self.assertEqual(
AssertionError: 946722630012 != 946693830012.0

----------------------------------------------------------------------
Ran 679 tests in 0.346s
```

**Comment by felixonmars** [comment]
Still appears in 3.20.0.

**Comment by pcorpet** [comment]
I can confirm the bug is due to a different timezone. I'll try to fix the timezone for this test or expect the proper result.
