### ISSUE TITLE
count_documents can't handle timezone-aware datetimes with tz_aware=True

### ISSUE THREAD

**Issue by languitar** [mongomock/mongomock#637]
```
>>> import mongomock
>>> from datetime import datetime, timezone
>>> client = mongomock.MongoClient(tz_aware=True)
>>> client.db.coll.count_documents({"foo": {"$gt": datetime.now(tz=timezone.utc)}})
0
>>> doc = {"foo": datetime.now(tz=timezone.utc)}
>>> client.db.coll.insert_one(doc)
<pymongo.results.InsertOneResult object at 0x7f905015c240>
>>> client.db.coll.count_documents({"foo": {"$gt": datetime.now(tz=timezone.utc)}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/collection.py", line 1360, in count_documents
    doc_num = len(list(self._iter_documents(filter)))
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/collection.py", line 1193, in <genexpr>
    if filter_applies(filter, document))
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 46, in filter_applies
    return _Filterer().apply(search_filter, document)
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 120, in apply
    is_match = all(
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 122, in <genexpr>
    self._operator_map[operator_string](doc_val, search_val) or
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 261, in <lambda>
    return lambda v, l: v is not NOTHING and f(v, l)
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 378, in func
    return f(doc_val, search_val)
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 272, in _wrapped
    return bson_compare(op, a, b, can_compare_types=False)
  File "/home/languitar/src/preprod-sync/.venv/lib/python3.8/site-packages/mongomock/filtering.py", line 317, in bson_compare
    return op(a, b)
TypeError: can't compare offset-naive and offset-aware datetimes
```

This happens with version 3.19.0

**Comment by gwainer** [comment]
I may have stumbled in the same problem, but with another cause. This time using `$match` in aggregation. 

Version 3.19.0

Similar example:

```
>>> import mongomock
>>> from datetime import datetime, timezone
>>> client = mongomock.MongoClient(tz_aware=True)
>>> client.db.coll.aggregate([{'$match': {'foo': {'$lte': datetime.utcnow()}}}])
<mongomock.command_cursor.CommandCursor object at 0x10c4fe710>
>>> client.db.coll.insert_one({"foo": datetime.now(tz=timezone.utc)})
<pymongo.results.InsertOneResult object at 0x10c50b2d0>
>>> client.db.coll.aggregate([{'$match': {'foo': {'$lte': datetime.utcnow()}}}])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/collection.py", line 1658, in aggregate
    return aggregate.process_pipeline(in_collection, self.database, pipeline, session)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/aggregate.py", line 1075, in process_pipeline
    collection = handler(collection, database, options)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/aggregate.py", line 1040, in <lambda>
    '$match': lambda c, d, o: [doc for doc in c if filtering.filter_applies(o, doc)],
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/aggregate.py", line 1040, in <listcomp>
    '$match': lambda c, d, o: [doc for doc in c if filtering.filter_applies(o, doc)],
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 46, in filter_applies
    return _Filterer().apply(search_filter, document)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 125, in apply
    for operator_string, search_val in iteritems(search)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 125, in <genexpr>
    for operator_string, search_val in iteritems(search)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 261, in <lambda>
    return lambda v, l: v is not NOTHING and f(v, l)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 378, in func
    return f(doc_val, search_val)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 272, in _wrapped
    return bson_compare(op, a, b, can_compare_types=False)
  File "/Users/gabrielcw/.pyenv/versions/3.7.6/envs/tqtq-api-env/lib/python3.7/site-packages/mongomock/filtering.py", line 317, in bson_compare
    return op(a, b)
TypeError: can't compare offset-naive and offset-aware datetimes
```
