### ISSUE TITLE
RuntimeError when mutating while iterating an OrderedDict

### ISSUE THREAD

**Issue by denivyruck** [mongomock/mongomock#694]
Hi all. I have a **multithreaded** test which is yielding me some `RuntimeErrors (RuntimeError: OrderedDict mutated during iteration)`. I couldn't isolate the issue yet, but I thought it would be helpful to already share it. I found on `store.py` there's a lock being used for the `setitem` but not for the `delitem`. That ringed me a bell but it didn't fix the issue. 

**Version: 3.22.0**

```Python
Traceback (most recent call last):
  File "[...]", line 278, in safe_bulk_write
    result = [...].bulk_write(ops)
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 1794, in bulk_write
    return BulkWriteResult(bulk.execute(), True)
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 322, in execute
    op_result = execute_func()
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 169, in exec_update
    result = collection._update(spec=selector, document=document,
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 621, in _update
    for existing_document in itertools.chain(self._iter_documents(spec), [None]):
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 1263, in _iter_documents
    return (document for document in list(self._store.documents)
  File "[...]lib/python3.8/site-packages/mongomock/store.py", line 128, in documents
    for doc in six.itervalues(self._documents):
RuntimeError: OrderedDict mutated during iteration

Traceback (most recent call last):
  File "[...]", line 278, in safe_bulk_write
    result = [...].bulk_write(ops)
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 1794, in bulk_write
    return BulkWriteResult(bulk.execute(), True)
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 322, in execute
    op_result = execute_func()
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 169, in exec_update
    result = collection._update(spec=selector, document=document,
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 621, in _update
    for existing_document in itertools.chain(self._iter_documents(spec), [None]):
  File "[...]lib/python3.8/site-packages/mongomock/collection.py", line 1263, in _iter_documents
    return (document for document in list(self._store.documents)
  File "[...]lib/python3.8/site-packages/mongomock/store.py", line 127, in documents
    self._remove_expired_documents()
  File "[...]lib/python3.8/site-packages/mongomock/store.py", line 133, in _remove_expired_documents
    self._expire_documents(index)
  File "[...]lib/python3.8/site-packages/mongomock/store.py", line 152, in _expire_documents
    expired_ids = [
  File "[...]lib/python3.8/site-packages/mongomock/store.py", line 152, in <listcomp>
    expired_ids = [
RuntimeError: OrderedDict mutated during iteration
```

It's hard to provide some test data as it's not an error that happens often and the testcase is a bit noisy, but I'll let you know if I manage to isolate it.

**Comment by denivyruck** [comment]
I think this relates to #229. Was it fixed? Sorry I should've checked previous issues.

**Comment by theahura** [comment]
We're running into this issue using a TTL Index on mongomock. Does the lock added here only work for updates?
