### ISSUE TITLE
Update $set with operator $[] is not working

### ISSUE THREAD

**Issue by lucasrcezimbra** [mongomock/mongomock#712]
[Operator `$[]`](https://docs.mongodb.com/manual/reference/operator/update/positional-all/#---) should update all the elements of an array, but in Mongomock it's raising an exception.

Mongo behaviour:

```javascript
db.test.insertOne({'operations': [{'rating': 'A'}, {'rating': 'B'}]})
db.test.updateOne({}, {'$set': {'operations.$[].rating': 'C'}})
db.test.find()

// result: 
{
	"_id" : ObjectId("60abd72ff9feee3f87d8d04b"),
	"operations" : [
		{
			"rating" : "C"
		},
		{
			"rating" : "C"
		}
	]
}
```

Example:
```python
import mongomock

mongo = mongomock.MongoClient()
coll = mongo['db']['coll']
coll.insert_one({'operations': [{'rating': 'A'}, {'rating': 'B'}]})
coll.update_one({}, {'$set': {'operations.$[].rating': 'C'}})
```

Error: 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucas/workspace/test/.venv/lib/python3.6/site-packages/mongomock/collection.py", line 560, in update_one
    filter, update, upsert=upsert, hint=hint, session=session, collation=collation),
  File "/home/lucas/workspace/test/.venv/lib/python3.6/site-packages/mongomock/collection.py", line 649, in _update
    existing_document, v, spec, updater, subdocument)
  File "/home/lucas/workspace/test/.venv/lib/python3.6/site-packages/mongomock/collection.py", line 1230, in _update_document_fields_with_positional_awareness
    existing_document, v, spec, updater, subdocument)
  File "/home/lucas/workspace/test/.venv/lib/python3.6/site-packages/mongomock/collection.py", line 1206, in _update_document_fields_positional
    current_doc = current_doc[part]
TypeError: list indices must be integers or slices, not str
```

**Comment by adFrank** [comment]
@lucasrcezimbra I am facing the exact same problem. Any news on this?

**Comment by lucasrcezimbra** [comment]
@adFrank No news. I think the bug persists.
